config/routes.rb
Vincompare::Application.routes.draw do
  root to: 'vins#new'
  
  resources :vins, only: [:new, :create, :show]
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  attr_reader :password
  
  validates :email, uniqueness: true, presence: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  
  def reset_session_token!  
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return user if user && user.is_password?(password)
    nil
  end
  
  # setter method for password
  def password=(unencrypted_password)
    @password = unencrypted_password
    self.password_digest = BCrypt::Password.create(unencrypted_password)
  end
  
  # is_password? correct
  def is_password?(unencrypted_password)
    BCrypt::Password.new(self.password_digest).is_password?(unencrypted_password)
  end
  
  
  
end

app/models/vin.rb
# == Schema Information
#
# Table name: vins
#
#  id         :integer          not null, primary key
#  vin_number :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Vin < ActiveRecord::Base
  validates :vin_number, presence: true

  def check_vin
    CheckVin::VinValidator.check_num?(self.vin_number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
  include SessionsHelper
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )
    if @user
      login!(@user)
      redirect_to root_url
    else
      flash[:errors] = ["Incorrect username and/or password"]
      render :new
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      login!(@user)            
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  
  def user_params
    params.require(:user).permit(:email, :password)  
  end  
end

app/controllers/vins_controller.rb
class VinsController < ApplicationController

  def new
    @vin = Vin.new
  end

  def create
    @vin = Vin.new(vin_params)
    
    begin
      @vin.save if @vin.check_vin
      render :show
    rescue ArgumentError => e
      flash[:notice] = e.message
      redirect_to root_url
    end
  end

  def show
  end

  private

  def vin_params
    params.require(:vin).permit(:vin_number)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def login!(user)
    session[:session_token] = @user.reset_session_token! 
  end
  
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logged_in?
    !!current_user
  end
  
  def logout!
    current_user.reset_session_token! if logged_in?
    session[:session_token] = nil
  end
  
  def require_user
    redirect_to new_session_url unless logged_in?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <%= link_to 'Home', root_path %>
      <%= link_to 'About', page_path('about') %>
      <%= link_to 'Privacy', page_path('privacy') %>
      <%= link_to 'Terms', page_path('terms') %>
    </div>
    <div class="text-right col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <p>Created as a free tool for all. <a href="http://vincompare.com" class="orange">© VinCompare, <%= Time.now.year %>.</a></p>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "VinCompare" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "VinCompare - join us in our fight agaist vehicle fraud" %>">
  <%= csrf_meta_tags %>

  <!-- Meta -->
  <%= favicon_link_tag '/assets/favicon.png' %>
  <meta name="og:title" content="Compare VIN Reports to buy the best">
  <meta name="og:type" content="website">
  <meta name="og:url"  content="http://www.vincompare.com">

  <!-- Styles -->
  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <!--<#%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>-->

  <!-- Javascripts -->
  <%= javascript_include_tag "application" %>

</head>

app/views/layouts/_landing.html.erb
<main role="main">
  <div class="container">
    <div class="lead">

        <header>          
          <span class="glyphicon glyphicon-check logo"></span>
        </header>

        <h1>Finding the best History Report?</h1>
        <h2><em>Each vehicle is different.</em> Compare them side by side.</h2>

        <div class="call-to-action">
          <div class="signup-form">
            <%= render partial: 'vins/form' %>
          </div>
        </div>

        <div id="preview">
          <%= image_tag ('nice-car.png'), height: "160", class: 'pull-left col-lg-offset-1 home-vehicle-left' %>
          <%= image_tag ('audi-r8-new.png'), height: "160", class: 'pull-right home-vehicle-right' %>
        </div>
    </div>
    <div class="report-logo text-center">
      <small class="text-muted">Comparison includes:</small>
      <div class="row">
        <%= image_tag 'carfax-logo.png', height: '40', width: '180', class: 'carfax-logo pull-left col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-xs-offset-1' %>
        <%= image_tag 'http://www.vinaudit.com/images/logos/vinaudit.com.gif', width: '240', height: '60', class: 'col-lg-offset-2 col-lg-3 col-md-offset-1 col-md-4 col-sm-offset-1 col-sm-4 col-xs-offset-1 col-xs-4' %>
        <%= image_tag ('autocheck-logo.png'), width: '240', height: '50', class: 'col-lg-offset-1 col-lg-2 col-md-3 col-sm-3 col-xs-3' %>
      </div>
    </div>

  </div>
</main>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-default" role="navigation" style="margin-bottom:0;">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'VinCompare', root_path, class: 'navbar-brand' %>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', page_path('about') %></li>
        <% if logged_in? %>
          <li>Welcome <%= current_user.username %></li>
          <li><%= button_to 'Log Out', session_url %></li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_url %></li>
          <li><%= link_to 'Log In', new_session_url %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<%= render 'layouts/head' %>

<body>
  <% if current_page?('/') %>
    <%= render 'layouts/messages' %>
    <%= render 'layouts/landing' %>
  <% else %>    
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
  <% end %>  

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About VinCompare<% end %>
<% content_for :description do %>Join us in our fight again vehicle fraud<% end %>
<main role="main">
  <div class="container">
    <br />
    <h1>About Us</h1><br />
    <p>We are a team of vehicle enthusiast. Every vehicle purchased needs to get a detailed vehicle inspection coupled with a history report. However, a majority of vehicle purchases made
       were not inspected before the purchase and some blindly trust just a vehicle report. A buyer needs both - not one or the other.</p>
    <p>A fascinating research done by ABC News showed evidence that a vehicle history report is simply not sufficient. The source
       of information that is on the report are from various locations - and not all accidents are reported. This is a major issue - especially
       with a projected used car dealers revenue of $77.6 Billion in 2013 (based on Used Car Dealers in the US May 2013 by IBISWORLD).  </p>
    <p>The following is a video related to a vehicle history report provider:</p>
    <br />
    <p class="text-center"><iframe width="560" height="315" src="//www.youtube.com/embed/52-0JQcixp4" frameborder="0" allowfullscreen></iframe></p>
    <br />
    <p>Hence, VinCompare.com was created. We purchased vehicle reports from all vehicle history reports from the US and compare each report.
       We will release updates & findings that we notice from each report incrementally on our website:
      <ul>
        <li>Information Source</li>
        <li>Relevant / Useful Information</li>
        <li>Report Availability</li>
        <li>Prices</li>
        <li>Market Trust, and more</li>
      </ul>
    </p>
    <p>If you have any suggestions or advance knowledge that you would like to share, please contact us
       and we will get with you as soon as possible. Sooner rather than later, this will be an open source project
       and every information found will be released to the public.</p>
    <p>As buyers or sellers, we reserve the rights to gain a full understanding of a vehicle before a transaction.
       Join us in our fight against fraud.</p>
    <br />
	<p>PS: We are currently working with Edmunds to integrate their API into our platform. Very soon, you will be able to obtain vehicle information as well! :) </p>
  </div>
</main>

app/views/pages/privacy.html.erb
<% content_for :title do %>VinCompare Privacy Policy<% end %>
<% content_for :description do %>VinCompare Privacy Policy - we respect our users<% end %>
<main role="main">
  <div class="container">
      <br />
    <h1>Privacy Policy</h1><br />
    <p>VinCompare.com is owned by AS Flux, LLC. AS Flux, LLC (“VinCompare,” “we,” “our” or “us”)] is committed to protecting your privacy. This VinCompare.com privacy policy (the “Privacy Policy”) describes the information that we collect from you through the www.VinCompare.com website (including co-branded and framed versions of the website and its subsites, the “Website”), the purposes for which we use such information, with whom we may share such information, your choices regarding our use and sharing of such information, and the steps we take to protect your personal information. By accessing the Website, you are consenting to the information collection, use and sharing practices described in this Privacy Policy. IF YOU DO NOT AGREE TO THE TERMS OF THIS PRIVACY POLICY, PLEASE DO NOT USE THE WEBSITE. Please note that this Privacy Policy only applies to information collected on the Website and does not apply to information which we may collect on other websites owned or operated by VinCompare.com (other than co-branded websites identified as VinCompare.com, which are subject to this Privacy Policy), or by means other than on the Website.</p>

    <p><a href="#top" style="display:none;"></a>
      <a href="#gather">WHAT INFORMATION DO WE GATHER AND TRACK?</a><br />
      <a href="#cookies">COOKIES AND HOW WE USE THEM</a><br />
      <a href="#share">WITH WHOM MAY WE SHARE YOUR INFORMATION</a><br />
      <a href="#information">HOW DO WE USE THE INFORMATION WE GATHER AND TRACK?</a><br />
      <a href="#update">CORRECTING/UPDATING INFORMATION</a><br />
      <a href="#links">LINKS TO OTHER SITES</a><br />
      <a href="#safe">SAFE AND SECURE TRANSACTIONS</a><br />
      <a href="#correcting">CORRECTING/UPDATING INFORMATION</a><br />
      <a href="#feedback">FEEDBACK OR QUESTIONS</a><br />
      <a href="#updates">PRIVACY POLICY UPDATES</a><br />
    </p>
    <br />
    <p><strong><a name="gather">WHAT INFORMATION DO WE GATHER AND TRACK?</a></strong><a href="#top"><small>  (back to top) </small></a><br/>
      At VinCompare.com, we take your privacy very seriously. We are not in the business of disclosing your personally identifiable information to others without your express or implied consent. We record IP addresses (the Internet address of a computer) to track sessions on our Website. Tracking gives us an idea of which parts and pages of our site users are visiting, how often they visit them, and how long they spend there. We also track browser type and platform. We use this information to deliver customized information specific to a particular platform and to determine the &#8220;mix&#8221; of browser types accessing our Website. This information helps us make our Website operate correctly with your browser.</p>
    <p>However, if you:</p>
    <ul>
      <li>Purchase a product or service from www.VinCompare.com;</li>
      <li>Sign up for a mailing list or enter a contest;</li>
      <li>Fill out a survey, or sign onto a page that requires authorization; or</li>
      <li>Enter into any other transaction with us,</li>
    </ul>
    <p>You may be asked to provide us your name, e-mail address, mobile phone number, land-line phone number, fax number, postal address, credit card number (for purchases), and possibly other personal information. Additional demographic information may be optionally requested in order to improve our service to our customers. We may use the information you provide to:</p>
    <ul>
      <li>Keep you informed of new releases of our products;</li>
      <li>Provide helpful hints and tips on how to use our products;</li>
      <li>Make special offers that we extend only to our registered customers for VinCompare and other affiliate products;</li>
      <li>Improve our Website and the services we offer you;</li>
    </ul>
    <p>In addition, some of our products and services may include technology that, if an Internet or Wi-Fi connection is available, contacts VinCompare.com servers with basic information about your mobile phone or mobile data device and the operating system and the types of programs it is used with. In some instances and with some of our products, the location of your mobile phone may be collected and utilized by VinCompare.com to provide you with the best service possible.</p>

    <p><strong><a name="cookies">COOKIES AND HOW WE USE THEM</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      Cookies are unique text files that are sent to your browser from a web server. As you browse our Website, cookies are placed on your computer&#8217;s hard drive including when you download, register and/or purchase software. Cookies may include registration numbers for any or all of your registered VinCompare.com products. Because some cookies may contain registration number(s), they can be linked to personally identifiable information. VinCompare.com does not provide any personally identifiable information from cookie data to third parties. VinCompare.com may use a third party to analyze for VinCompare.com general Website statistics such as number of pages viewed, browser types, etc. obtained from cookies.</p>
    <p>Cookies are used by VinCompare.com for the following:</p>
    <ul>
      <li>To track the method of your referral to our Website;</li>
      <li>Anonymous statistical purposes;</li>
      <li>To track your site session and present information, graphics or hyperlinks based on your session and/or write information to submission forms when contacting VinCompare.com; and</li>
      <li>To present information, offers and invitations (surveys, beta programs, etc.) based on your product registration and improve your experience with the site.</li>
    </ul>

    <p><strong><a name="share">WITH WHOM MAY WE SHARE YOUR INFORMATION</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      We may collect, create and disclose to third parties aggregated, anonymous statistics regarding our sales, traffic analyses and other information regarding or collected through our Website. We may also sometimes engage agents, contractors, or other trusted businesses to perform services necessary to our operations (for example, delivery of products, distribution of e-mail, etc.). When we do, we may give them access to name, addresses or other information necessary for them to do their job for us, but not for any other purpose.</p>
    <p>In limited cases, we will share your registration information (name, address, mobile phone number, etc.) with the manufacturer or affiliate service provider of that product, when you buy a third-party product or services from us, or with other third-party affiliates. That manufacturer or affiliate then may use your data to contact you by email, text and or voice blast on your mobile device etc and might also share your data with others, depending upon that manufacturer&#8217;s or affiliate’s own privacy policy. By opting-in to this privacy policy on the registration page, you are providing us permission to share personal information about you with other companies for their marketing use. We believe that the manufacturers, affiliates, and other third parties whose products we promote or sell typically will respect your privacy; however, we don&#8217;t control what they do with data they receive from us. We therefore recommend that you check the privacy policy of any third-party manufacturer or affiliate whose products you choose to buy from us, including how to tell that manufacturer or affiliate your e-mail opt-out preferences, request to update or delete your data, etc. If you have any questions about the data we give to third-party manufacturers of products you buy from us or which specific manufacturers we share information with, please contact us directly. Finally, in the event our company or its assets were ever sold, our customer database naturally would be transferred to the new owner.</p>
    <p>Except as described above, and except as may be required by law, we will not disclose your personally identifiable information to others without your consent. In the event that VinCompare becomes involved in a merger, acquisition, or any form of sale of some or all of its assets, we will ensure the confidentiality of any personal information involved in such transactions.</p>

    <p><strong><a name="information">HOW DO WE USE THE INFORMATION WE GATHER AND TRACK?</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      The information collected may be used for processing orders, personalizing the shopping experience, contests, promotions, newsletters, announcements, special offers, etc.</p>

    <p><strong><a name="update">CORRECTING/UPDATING INFORMATION</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      If your personally identifiable information changes (such as your mobile phone number, postal address, and zip code), or if you no longer desire our service, we will endeavor to provide a way to correct, update or remove your personal data provided to us. This can be accomplished by contacting VinCompare.com via e-mail, fax, phone, or US mail communication.</p>

    <p><strong><a name="links">LINKS TO OTHER SITES</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      The VinCompare.com site contains links to other websites. We cannot guarantee your privacy once you leave our Website. We are not responsible for the privacy policies, practices or content of websites with links on our site. We encourage you to read the posted privacy statement whenever interacting with any website.</p>

    <p><strong><a name="safe">SAFE AND SECURE TRANSACTIONS</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      Protecting your order information is important to us and we make every effort to protect your online order information by using Secure Sockets Layer (SSL) technology. However, some firewalls and certain versions of browsers don&#8217;t permit communication through secure servers.</p>

    <p><strong><a name="correcting">CORRECTING/UPDATING INFORMATION</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      If your personally identifiable information changes (such as your mobile phone number, postal address, and zip code), or if you no longer desire our service, we will endeavor to provide a way to correct, update or remove your personal data provided to us. This can be accomplished by contacting VinCompare.com via e-mail, fax, phone, or US mail communication.</p>

    <p><strong><a name="feedback">FEEDBACK OR QUESTIONS</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      If you have any questions or feedback regarding our privacy statement, please contact us via email:</p>
    <address>
      <a href="mailto:#">privacy@vincompare.com</a>
    </address>

    <p><strong><a name="updates">PRIVACY POLICY UPDATES</a></strong><a href="#top"><small>  (back to top) </small></a><br />
      You should check back for updates to this privacy policy since we reserve the right to update it from time to time without notice. Your continued use of the Website www.VinCompare.com following the posting of updates to this Privacy Policy will mean you accept those updates. This page was last modified on August 29th, 2013.</p>
    <br />
  </div>
</main>

app/views/users/new.html.erb
<% content_for :title do %>Sign Up at VinCompare<% end %>
<% content_for :description do %>Join us in our fight again vehicle fraud<% end %>
<main role="main">
  <div class="container">
    <%= form_for @user, url: { action: 'create' } do |f| %>
    
      <%= f.label :email %>
      <%= f.email_field :email %><br>
      
      <%= f.label :password %>
      <%= f.password_field :password %><br>
      
      <%= f.submit %>
    <% end %>      
  </div>
</main>

app/views/vins/_all_check_ok.html.erb
<td><span class="glyphicon glyphicon-ok"></span></td>
<td><span class="glyphicon glyphicon-ok text-info"></span></td>
<td><span class="glyphicon glyphicon-ok"></span></td>

app/views/vins/_compare_header.html.erb
<header class="navbar navbar-default" role="navigation" style="margin-bottom:0;">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/" class="navbar-brand">VinCompare</a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'About', page_path('about') %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/vins/_comparison_table.html.erb
<table class="table table-stripped table-hover table-bordered">
  <thead>
  <tr>
    <th></th>
    <th>FastVIN</th>
    <th>AutoCheck</th>
    <th>CarFax</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td>Vehicle Specifications</td>
    <%= render :partial => 'all_check_ok' %>
  </tr>
  <tr>
    <td>Title Information</td>
    <%= render :partial => 'all_check_ok' %>
  </tr>
  <tr>
    <td>Junk/Salvage/Insurance</td>
    <%= render :partial => 'all_check_ok' %>
  </tr>
  <tr>
    <td>Brand Information</td>
    <%= render :partial => 'all_check_ok' %>
  </tr>
  <tr>
    <td>Airbag Deployment</td>
    <%= render :partial => 'all_check_ok' %>
  </tr>
  <tr>
    <td>Fleet/Rental/Lease</td>
    <td></td>
    <td><span class="glyphicon glyphicon-ok text-info"></span></td>
    <td><span class="glyphicon glyphicon-ok"></span></td>
  </tr>
  <tr>
    <td>Police Records</td>
    <td></td>
    <td><span class="glyphicon glyphicon-ok text-info"></span></td>
    <td><span class="glyphicon glyphicon-ok"></span></td>
  </tr>
  <tr>
    <td>Auto Auction</td>
    <td></td>
    <td><span class="glyphicon glyphicon-ok text-info"></span></td>
    <td><span class="glyphicon glyphicon-ok"></span></td>
  </tr>
  <tr>
    <td>Loan/Lien</td>
    <td></td>
    <td><span class="glyphicon glyphicon-ok text-info"></span></td>
    <td><span class="glyphicon glyphicon-ok"></span></td>
  </tr>
  <tr>
    <td>Police Case #</td>
    <td></td>
    <td><span class="glyphicon glyphicon-ok text-info"></span></td>
    <td></td>
  </tr>
  <tr>
    <td>Unlimited Reports</td>
    <td></td>
    <td><span class="glyphicon glyphicon-ok text-info"></span></td>
    <td></td>
  </tr>
  <tr>
    <td>Price</td>
    <td>$12.95</td>
    <td>$29.99</td>
    <td>$39.99</td>
  </tr>
  <tr>
    <td>Get More Info</td>
    <td><a href="http://www.jdoqocy.com/click-7084116-11347306/vin-search?vin=<%= @vin.vin_number %>" target="_blank"><button type="button" class="btn btn-primary btn-block">Check</button></a></td>
    <td><a href="http://www.autocheck.com/consumers/gatewayAction.do?vin=<%= @vin.vin_number %>&siteID=CJ7084116&WT.mc_id=CJ&sslRedirect=noRedirect" target="_blank"><button type="button" class="btn btn-primary btn-block">Check</button></a></td>
    <td><a href="http://www.carfax.com/" target="_blank"><button type="button" class="btn btn-primary btn-block">Check</button></a></td>
  </tr>
  </tbody>
</table>

app/views/vins/_form.html.erb
<%= form_for @vin, method: :post do |f| %>
  <%= f.text_field :vin_number, placeholder: 'Enter VIN Number', required: 'true' %>
  <button type="submit">
    <span class="glyphicon glyphicon-search white icon"></span>
  </button>
<% end %>

app/views/vins/compare.html.erb
<%= render 'layouts/navbar' %>

<main role="main">
  <div class="container">
    <div class="lead">
      <h2>Checking sources to compare VIN <%= @vin.vin_number %>...</h2>
      <div class="progress"></div>
      <%= render 'vins/comparison_table' %>
    </div>
  </div>
</main>

app/views/vins/show.html.erb
<main role="main">
  <div class="container">
    <div class="lead">
      <h2>Checking sources to compare VIN <%= @vin.vin_number %>...</h2>
      <div class="progress"></div>
      <%= render 'vins/comparison_table' %>
    </div>
  </div>
</main>